server:
  port: 3003
  template: config.tmpl

configs:
    8000:
        - name: ss8000
          type: ss
          server: proxy.gitez.cc
          port: 8000
          cipher: aes-256-cfb
          password: 8000
          udp: true
        - name: ss7000
          type: ss
          server: proxy.gitez.cc
          port: 7000
          cipher: aes-256-cfb
          password: 7000
          udp: true
    8001:
        - name: ss8001
          type: ss
          server: proxy.gitez.cc
          port: 8001
          cipher: aes-256-cfb
          password: 8001b
          udp: true
        - name: ss7001
          type: ss
          server: proxy.gitez.cc
          port: 7001
          cipher: aes-256-cfb
          password: 7001b
          udp: true
    8002:
        - name: ss8002
          type: ss
          server: proxy.gitez.cc
          port: 8002
          cipher: aes-256-cfb
          password: 8002
          udp: true
        - name: ss7002
          type: ss
          server: proxy.gitez.cc
          port: 7002
          cipher: aes-256-cfb
          password: 7002
          udp: true
    8003:
        - name: ss8003
          type: ss
          server: proxy.gitez.cc
          port: 8003
          cipher: aes-256-cfb
          password: aaxc8003!!
          udp: true
        - name: ss7003
          type: ss
          server: proxy.gitez.cc
          port: 7003
          cipher: aes-256-cfb
          password: aaxc7003!!
          udp: true
    8004:
        - name: ss8004
          type: ss
          server: proxy.gitez.cc
          port: 8004
          cipher: aes-256-cfb
          password: 8004d
          udp: true
        - name: ss7004
          type: ss
          server: proxy.gitez.cc
          port: 7004
          cipher: aes-256-cfb
          password: 7004d
          udp: true
    8005:
        - name: ss8005
          type: ss
          server: proxy.gitez.cc
          port: 8005
          cipher: aes-256-cfb
          password: 8005e
          udp: true
        - name: ss7005
          type: ss
          server: proxy.gitez.cc
          port: 7005
          cipher: aes-256-cfb
          password: 7005e
          udp: true
    8006:
        - name: ss8006
          type: ss
          server: proxy.gitez.cc
          port: 8006
          cipher: aes-256-cfb
          password: 8006f
          udp: true
        - name: ss7006
          type: ss
          server: proxy.gitez.cc
          port: 7006
          cipher: aes-256-cfb
          password: 7006f
          udp: true

mysql:
  enable: false
  dsn: <user>[:password]@tcp(localhost)/
  maxIdleConns: 0
  maxOpenConns: 50
mongodb:
  enable: false
  url: mongodb://localhost:27017

log:
  level: debug
  logfile: ''
  showFullTime: true
  reportCaller: false

cors:
  allowOrigins: ['*']
  allowMethods: [ 'GET', 'POST']
  allowHeaders: ['Origin', 'Content-Length', 'Content-Type']
  maxAge: 43200