[server]
port=8080

template="config.tmpl"
[configs]
    [configs.8000]
    server="sh.eagle711.win"
    cipher="aes-256-cfb"
    password="8000"

    [configs.8001]
    server="sh.eagle711.win"
    cipher="aes-256-cfb"
    password="8001b"

    [configs.8002]
    server="sh.eagle711.win"
    cipher="aes-256-cfb"
    password="8002"

    [configs.8003]
    server="sh.eagle711.win"
    cipher="aes-256-cfb"
    password="aaxc8003!!"

    [configs.8004]
    server="sh.eagle711.win"
    cipher="aes-256-cfb"
    password="8004d"

    [configs.8005]
    server="sh.eagle711.win"
    cipher="aes-256-cfb"
    password="8005e"

    [configs.8006]
    server="sh.eagle711.win"
    cipher="aes-256-cfb"
    password="8006f"

[mysql]
enable = false
# <user>[:password]@tcp(address)/<Database>
# address: host[:port] | /path/to/unix/socket/file
dsn="<user>[:password]@tcp(localhost)/<Database>"
maxIdleConns=0
maxOpenConns=50

[mongodb]
enable = false
url="mongodb://localhost:27017"

[jwt]
headerName = "token"
# key to sign jwt
key="<secret key>"
# token 过期时间，单位小时；为零时表示不过期
exp = 24

[tls]
enable = false
certFile = "cert.pem"
keyFile = "cert.key"

[log]
# available values :"debug" "info" "error" "fatal" "panic"
level = "debug"
# logfile = "clashsub.log"
logfile = ""
showFullTime = true
reportCaller = false

[cors]
# "*" means allow all origins
allowOrigins = [ "*" ]
allowMethods = [ "GET", "POST" ]
allowHeaders = [ "Origin", "Content-Length", "Content-Type" ]
# unit: second
maxAge = 43200
